#!/bin/sh

# Timing the script!
start=$(date +%s)

# Now with colours!
NCLR='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'

# Error msg
errorMsg() {
    echo "[-] Error: $1" >&2;
}

# Usage
usage() {
    echo
    printf 'Usage: %s <Target-IP / Targets file> <Output filename> ' "$(basename "$0")"
    printf '%s\t-v : %s Verbose\n -A\tAggresive\n -h\tDisplay this help and exit -t\tTarget(s) to attack. It can be a targets file.' "$YELLOW" "$NCLR"
    printf '%s\t-v : %s Verbose\n -A\tAggresive\n -h\tDisplay this help and exit -t\tTarget(s) to attack. It can be a targets file.' "$YELLOW" "$NCLR"
}

waitforit() {
	pids=($@)
	for p in ${pids[*]}; do
		wait $p
	done
}


noDnsResolv=0
dnsServers="-n"

while getopts "-h:-v:-a:-t:" flag
do
    case "${flag}" in
    -h)  
    usage; 
    exit 1;
    ;;

    -v)  
    VERBOSE_FLAG="-vv";
    COMP_NAME="$COMP_NAME""_verbose";
    ;;

    -a)  
    AGGRESIVE_FLAG="-A";
    COMP_NAME="$COMP_NAME""_aggressive";
    ;;

    t)	
    TARGET_NAME=${OPTARG};
    verboseMsg "Target name is '${OPTARG}'";
	;;

    *) 
    errorMsg "Invalid options provided";
	usage;
	;;
    esac
done


if [ -n "$TARGET_NAME" ]; then
IP="$1"
else
errorMsg "You must provide a Target hostname/IP address to start the attack"
usage
fi

if [ -n "$2" ]; then
NAME="$2"
else
errorMsg "Second argument must be name of output file"
fi

printf "[+] Scanning %s for any TCP open ports..." "$IP"
# printf "${green}[+] Scanning %s for any TCP open ports..." "$IP"
PORTS=$(nmap --min-rate=2000 -p- -T5 "$IP" | grep "^[0-9]" | cut -d '/' -f 1 | tr '\n' ',' | sed "s/,$//")
#PORTS=$(nmap -p- --min-rate=1000 -T4 "$IP" | grep "^[0-9]" | cut -d '/' -f 1 | tr '\n' ',' | sed "s/,$//")

# printf "[+] Done! Here is a summary of the open ports in %s:\n" "$IP"

# for PORT in $(echo "$PORTS" | tr ',' '\n')
# do 
#     echo "Port $PORT."
# done


FINAL_NAME="${NAME}${COMP_NAME}"

# echo "${yellow}[+] Procceeding to scan the open ports with your settings...${reset}"
echo "[+] Procceeding to scan the open ports with your settings..."

nmap -sS -v "$AGGRESIVE_FLAG" "$VERBOSE_FLAG" -oN "${FINAL_NAME}".scan -p"$PORTS" "$IP"

# printf "${green}[+] Done! you file has been saved as %s.scan" "$FINAL_NAME"
printf "[+] Done! you file has been saved as %s.scan" "$FINAL_NAME"

# Getting runtime
end=$(date +%s)
runtime=$((end - start))
printf "\n[+] It took %s seconds to scan your target!!" "$runtime"
