#!/bin/sh

# ---------- Constants ----------
RESTORE="\033[0m"
RED="\033[031m"
GREEN="\033[32m"
YELLOW="\033[33m"
START=$(date +%s) # Timing the execution 

# ---------- Functions ----------

# Print usage and exit
usage() {
    echo
    printf "${GREEN}Usage: ${RESTORE}%s <Target-IP / Targets file> <Output filename>\n" "$(basename "$0")"
    printf "${YELLOW}\t-h : ${RESTORE} Display this help and exit.\n"
    printf "${YELLOW}\t-o : ${RESTORE} Change the default output directory from [/cwd/autoNmap/<tool output>] to [<your/path>/autoNmap/<tool output>]\n"
    printf "${YELLOW}\nExamples: \n\t%s 10.129.121.60 TEST-012 \n\t%s 192.168.0.254 router\n" "$(basename "$0")" "$(basename "$0")"
    exit 1
}

# Print red error messages and call usage
error_msg() {
    printf "${RED}[-] Error: $1 %s" >&2 
    usage
}

# Optional parameters
while getopts "hp" flag
do
    case "${flag}" in
    h) usage;;
    p) ;; #Placeholder, for the future
    *) error_msg "Invalid options provided"; usage;;
    esac
done

# Wait for other processes to finish
# TODO wait_for_it() {}

# Quickly scan all TCP ports and save them to $PORTS
ports_sweep() {
    printf "${YELLOW}Starting nmap scan against ${RESTORE}%s${GREEN} for any TCP open ports..." "$IP"
    PORTS=$(nmap --min-rate=2000 -p- -T5 "$IP" | grep "^[0-9]" | cut -d "/" -f 1 | tr "\n" "," | sed "s/,$//")

    echo "$PORTS" > "$dir""$name".txt
    printf "${GREEN}[+] Done! Open ports in ${YELLOW}%s${GREEN} saved as ${YELLOW}%s.txt${RESET}\n" "$IP" "$dir$name"   
}

# Proceed with a quick normal scan 
normal_scan() { 
    nmap -sV -vv -oA "$dir$name" -p"$PORTS" "$IP"
}

# Proceed with an aggressive scan
#TODO aggressive_scan() {}

# UDP scan
#TODO udp_scan() {}

# Let the fun begin!
main() {
    ports_sweep
    normal_scan
}

# ---------- Final checks, ensuring everything is ready to run ----------

# Ensure theres a target
if [ -n "$1" ]; then
    IP="$1"
else
    errorMsg "You must provide a Target hostname/IP address to start the attack"
fi

# Ensure $IP is an IP or a URL
if ! expr "${IP}" : "^\([0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\)$" >/dev/null && \
   ! expr "${IP}" : "^\(\([[:alnum:]-]\{1,63\}\.\)*[[:alpha:]]\{2,6\}\)$" >/dev/null; then
    error_msg "Invalid IP or URL!"
    usage
fi

# Ensure output files are named
if [ -n "$2" ]; then
    name="$2"
else
    errorMsg "Second argument must be name of output files"
fi

# Ensure output directory is correctly set and exists
## TODO: create option to set custom directory if launched autonomously outside Docker
pwd=$(pwd)
if [ ! -d "${pwd}/nmap" ]; then
    mkdir "$pwd/nmap"
fi
dir="$pwd/nmap/"


# nmap -sS -v "$AGGRESIVE_FLAG" "$VERBOSE_FLAG" -oN "${FINAL_NAME}".scan -p"$PORTS" "$IP"
# printf "%s[+] Done! your file has been saved as %s.scan" "$GREEN" "$FINAL_NAME"


# ---------------------------------
#                START
# ---------------------------------
echo
printf "${GREEN}---------- Running with the following settings: ----------\n"
printf "[+] Using ${RESTORE}'%s'${GREEN} as target\n" "$IP"
printf "[+] Using ${RESTORE}'%s'${GREEN} as name for the output files\n" "$name"
printf "\n${YELLOW}[!] Start!\n"
printf "${RESTORE}"

main

# Getting timing score
END=$(date +%s)
runtime=$((END - START))
printf "\n${GREEN}[+] It took %s seconds to scan your target!!\n" "$runtime"